### ISSUE TITLE
How to easily generate a JSON file?

### ISSUE THREAD

**Issue by majouji** [listsfordesign/Lists#57]
Would be useful to document how to easily generate a JSON from a single text list.

I wanna contribute but I’m not sure how to turn a simple list into a JSON file that respects this specific formatting (read: I’m a super n00b). Thanks!

**Comment by vltrajvlien** [comment]
Hi, thanks for the suggestion. I'm going to work on a little tool that converts a raw list into a properly formated JSON file.

**Comment by majouji** [comment]
Any update on this? @jperriere
