### ISSUE TITLE
Filtering items in the lists.design main view

### ISSUE THREAD

**Issue by Eccenux** [listsfordesign/Lists#86]
Hi.

Could you add some filtering to the lists.design main view?

If you want you can use my [ViewFilter.js](https://gist.github.com/Eccenux/5a72d124f2379d36760c195b07002a6b) for that.

Before `gridList` add:
```html
<div id="controls"></div>
```
After the list add (probably on bottom)
```html
<script src="js/ViewFilter.js"></script>
<script type="text/javascript">
	// this will be a filter for symbol
	var sectionFilter = new ViewFilter("#controls", ".gridList .list");
	// we just filter by title
	sectionFilter.itemToText = function(item) {
		return item.querySelector('h1').textContent;
	};
	// i18n
	sectionFilter.placeholderText = function() {return "Filter"}
	// on load create controls and pre-parse items
	sectionFilter.init();
</script>
```

You probably might want to do some styling of controls that are added :-).

**Comment by vltrajvlien** [comment]
Hey @Eccenux, thanks for the help, interesting solution. We're going to launch a new website soon, which has filtering (it's already built). Cheers!
